version: '3'
services:
  batch:
    build: .
    container_name: dev_container
    tty: true
    volumes:
      - ./app:/app

  sftp:
    image: atmoz/sftp
    container_name: sftp_server
    tty: true
    volumes:
        - ./app/remote:/home/sftp_user/uploaded
    ports:
        - "10220:22"
    command: sftp_user:Passw0rd:1001
